### ISSUE TITLE
 Clam never detect php code inside image file or ico file

### ISSUE THREAD

**Issue by araviaravi** [Cisco-Talos/clamav-faq#111]
![home-11-split-4-550x550-2x](https://user-images.githubusercontent.com/20757822/61811243-b6e30180-ae5e-11e9-95f0-61f447e5d960.jpg)

Clam never detect php code inside image file or ico file

set htaccess as below:
<Files "home-11-split-4-550x550-2x.jpg">
AddHandler application/x-httpd-php .jpg
</Files>

load php payload as home-11-split-4-550x550-2x.jpg

Sample file is attached

**Comment by micah-at-talos** [comment]
This is the wrong ticket queue for clamav issues. Please report such issues here: https://bugzilla.clamav.net/enter_bug.cgi?product=ClamAV
