### ISSUE TITLE
Windows user manual service instructions

### ISSUE THREAD

**Issue by micahsnyder** [Cisco-Talos/clamav-faq#117]
The Windows user manual instructions could really use instructions on how to set up ClamAV as a service on Windows.

I would suggest either:
1) adding a section at the bottom of the [installation instructions](https://github.com/Cisco-Talos/clamav-faq/blob/master/manual/UserManual/Installation-Windows.md) about how to install clamd/freshclam to run a service, or
2) place a link there and add a page under the [Usage directory](https://github.com/Cisco-Talos/clamav-faq/tree/master/manual/UserManual/Usage).

**Comment by mmanna-sapfgl** [comment]
@micah-at-talos  Please assign this to my name. I have got a forked repo for this.

**Comment by DaveGitRDone** [comment]
Hello:  
I'm running a Windows Service that launches the clamd.exe and then periodically monitors (via PING).  The code snippet below is my attempt to make clamd.exe run like a "background" process.  Unfortunately, clamd goes unresponsive after 5-12 hours.  FWIW - here's my recipe.  Let me know if you'd like me to try anything and share results.  

                _processStartInfo = new ProcessStartInfo(Path.Combine(path, "clamd.exe")) {
                    UseShellExecute = false,
                    RedirectStandardError = true,
                    RedirectStandardInput = true,
                    RedirectStandardOutput = true,
                    CreateNoWindow = true,
                    ErrorDialog = false,
                    WorkingDirectory = path,
                    WindowStyle = ProcessWindowStyle.Hidden
                };
               _process = Process.Start(_processStartInfo);

Thanks,
-Dave

**Comment by mmanna-sapfgl** [comment]
> Hello:
> I'm running a Windows Service that launches the clamd.exe and then periodically monitors (via PING). The code snippet below is my attempt to make clamd.exe run like a "background" process. Unfortunately, clamd goes unresponsive after 5-12 hours. FWIW - here's my recipe. Let me know if you'd like me to try anything and share results.
> 
> ```
>             _processStartInfo = new ProcessStartInfo(Path.Combine(path, "clamd.exe")) {
>                 UseShellExecute = false,
>                 RedirectStandardError = true,
>                 RedirectStandardInput = true,
>                 RedirectStandardOutput = true,
>                 CreateNoWindow = true,
>                 ErrorDialog = false,
>                 WorkingDirectory = path,
>                 WindowStyle = ProcessWindowStyle.Hidden
>             };
>            _process = Process.Start(_processStartInfo);
> ```
> 
> Thanks,
> -Dave

APologies but this ticket is to update documentation. Once a PR has been approved, you can refer to the FAQ section and see if the document helps.

**Comment by DaveGitRDone** [comment]
Hello:

Sorry. I've been doing a lot of troubleshooting clamd.exe in Windows and
Micah directed me to your GitHub site and suggested I reach out to you.
I'm new to GitHub and wasn't sure how to go about getting in touch.  I'll
try and log into Github and remove my posting.

"Recently we recruited the help of a user, Manna (username: mmanna-sapfgl)
to write instructions for how to run ClamAV as a service on Windows.
Here's the Github ticket:
https://github.com/Cisco-Talos/clamav-faq/issues/117.  He only just started
a day or two ago so I'm not sure how long until he'll have completed
content.  If you want to reach out to him to work with him on it, or to get
ideas from him -- I'm sure he would appreciate the collaboration."

Thanks,
-Dave

**Comment by micahsnyder** [comment]
Manna's comments in the associated PR are probably correct -- that Windows Service setup is outside the context of ClamAV.  In the future, if we are able to add built-in Windows service abilities for clamd, freshclam programs, then we'll have to add instructions on how to use the built-in service features.
