### ISSUE TITLE
purging/deleting old virus definitions

### ISSUE THREAD

**Issue by robina80** [Cisco-Talos/clamav-faq#130]
hi all,

i have installed clamav using this link with squid so it can do realtime virus scanning on prople browsing the internet via this proxy

https://hostpresto.com/community/tutorials/how-to-install-clamav-on-centos-7/

but obviously now my sdb is full and i have no space left

i was wondering is there a way into deleting old virus definitions/databases as clamav must save them somewhere

thanks,

rob

**Comment by micahsnyder** [comment]
Hi @robina80,

It looks like the centos epel package places our databases in a non-standard location, in `/var/lib/clamav`.  You should be able to delete that directory to free up space on your device.

Regards,
Micah

**Comment by micahsnyder** [comment]
For future questions, please consider using our [Discord, IRC, or users mailing lists](https://www.clamav.net/documents/introduction).

**Comment by robina80** [comment]
i found out what was eating all my space on sdb1, i ran the "du -sh" command on all dirs, it was my squid logs, so i just did this and reloaded squid

echo "" > /usr/local/squid/var/logs/access.log
echo "" > /usr/local/squid/var/logs/cache.log/usr/local/squid/sbin/squid -k reconfigure
