### ISSUE TITLE
Block/Allow List

### ISSUE THREAD

**Issue by nicoletteeaton** [Cisco-Talos/clamav-faq#132]
Text needs to be updated throughout this repo to change "Blacklist" to "Block List" and change "Whitelist" to "Allow List".

**Comment by micahsnyder** [comment]
Agreed!  We have a task in Jira to do this for the clamav-devel codebase as well.

**Comment by vrtadmin** [comment]
@micahsnyder do you want to eat this task?  and me review?  or?

**Comment by micahsnyder** [comment]
Sounds good, I'll take care of it.  From what I can tell, this can be done independently of the equivalent changes in clamav-devel as the terms are not not a part of the API. 👍
