### ISSUE TITLE
PUA categories outdated?

### ISSUE THREAD

**Issue by ASchmidt1** [Cisco-Talos/clamav-faq#134]
The default config file references
https://github.com/vrtadmin/clamav-faq/blob/master/faq/faq-pua.md
as the official list of PUA categories.

However, ClamAV is reporting names such as "PUA.Win.Downloader.Aiis-6803892-0", that don't seem to match up with any of the categories in the above document?

**Comment by micahsnyder** [comment]
Hi @ASchmidt1 yes the PUA categories are a little outdated.  I'm asking the team responsible for signatures and categories to help. In this specific case you've found a PUA signature that probably shouldn't exist or should be renamed as it's been given a malware name, not a PUA name.  I'm told the system which would've added that has been fixed so it won't add any more, but that some such signatures need to be cleaned up.  I'll leave this ticket open for now and try to check in again about updated PUA categories when I have more information or have the new categories and can update them.

**Comment by micahsnyder** [comment]
I'm pinging the other team about this again, after working on https://bugzilla.clamav.net/show_bug.cgi?id=12632
Hopefully we can resolve this soon.

**Comment by finchy** [comment]
Closed with #153
