### ISSUE TITLE
recipe for clamscan failed

### ISSUE THREAD

**Issue by mo716** [Cisco-Talos/clamav-faq#135]
Hi! I have been trying to install ClamAV  (as root) in an Ubuntu 16.04.6 LTS machine but I keep running into this mistake after executing 

`make -j2`

...
collect2: error: ld returned 1 exit status
Makefile:652: recipe for target 'clamscan' failed
make[1]: *** [clamscan] Error 1
make[1]: Leaving directory '/mnt/volume/clamav/clamav-0.102.4/clamscan'
Makefile:853: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

In case it helps, I also got these messages when running some previous commands, which might be related to my main issue:

`./configure --enable-check`

...
configure: Summary of detected features follows
              OS          : linux-gnu
              pthreads    : yes (-lpthread)
configure: Summary of miscellaneous features
              check       : -lcheck_pic -pthread -lrt -lm -lsubunit
              fanotify    : yes
              fdpassing   : 1
              IPv6        : yes
              openssl     : /usr
              libcurl     : /usr
configure: Summary of optional tools
              clamdtop    : yes (-lncurses)
              milter      : no (missing libmilter) (disabled)
              clamsubmit  : yes (libjson-c-dev found at /usr, linking=dynamic)
              clamonacc   : yes (auto)
configure: Summary of engine performance features
              release mode: yes
              llvm        : no (disabled)
              mempool     : yes
configure: Summary of engine detection features
              iconv       : yes
              bzip2       : ok
              zlib        : yes (from system)
              unrar       : yes
              preclass    : yes (libjson-c-dev found at /usr, linking=dynamic)
              pcre        : /usr
              libmspack   : yes (Internal)
              libxml2     : yes, from /usr
              yara        : yes
              fts         : yes (libc)
configure: WARNING:
****** libjson-c is known to share symbol names with other JSON libraries
****** which may result in crashes for applications that use libclamav.
****** Consider using --with-libjson-static=path/to/libjson-c.a,
****** providing a json-c library that was compiled with CFLAGS="-fPIC".

Also, I have not been able to solve this problem with check-devel

`sudo apt-get install check-devel`

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package check-devel

Please note, that I ran all as root user. 
Thank you very much for your help in advance! :)

**Comment by micahsnyder** [comment]
Hi @mo716 this isn't really the proper place to seek support. This is an issue tracker for the clamav documentation. For support, please use either
- The clamav users mailing list: https://lists.clamav.net/mailman/listinfo/clamav-users
- The #clamav irc room on irc.freenode.net
- The ClamAV Discord server (which is linked with the #clamav irc room via bots): https://discord.gg/sGaxA5Q

If you believe you've encountered a bug in clamav, consider creating a ticket here: https://bugzilla.clamav.net/enter_bug.cgi?product=ClamAV 

Regarding your specific issue, it seems as though you haven't pasted enough of the error output from your build to tell what is going on.  A link to pastebin (or equivalent) of the entire build output will probably be needed to help.
