### ISSUE TITLE
Binary analysis?

### ISSUE THREAD

**Issue by aug2uag** [Cisco-Talos/clamav-faq#138]
Curious to know if ClamAV can assess binary files, and if so where an example or documentation resources may be found.

**Comment by finchy** [comment]
Depending on what you mean by binary files, but yes, ClamAV can do that.

Thank you for your interest in ClamAV.  While we receive a great number of requests, we cannot answer them all individually.  We have thousands of people subscribed to our mailing lists, and it's better if you submit your questions to the appropriate mailing list at:

https://www.clamav.net/contact#ml

Please check out our ClamAV-Users mailing list there!  Thanks!
