### ISSUE TITLE
clamonacc (0.102.4) - ERROR: ClamClient: could not establish connection, Couldn't connect to server 

### ISSUE THREAD

**Issue by Likkrid** [Cisco-Talos/clamav-faq#139]
Hey Team,

I am facing an issue where I have clamd and clamonacc in place and running in parallel as different systemd units on the same NixOS system.

## Once the number of opened files by clamonacc process reaches a certain value (1045) with a lot of UNIX socket files I start seeing the following error:
```bash
ClamFanotif: internal error (failed to read data) ... Too many open files
ClamFanotif: waiting for consumer thread to catch up then retrying ...
ClamWorker: performing scanning on file ''
ERROR: ClamClient: could not establish connection, Couldn't connect to server
ClamMisc: $/proc/22824 vanished before UIDs could be excluded; scanning anyway
ClamFanotif: attempting to feed consumer queue
ClamFanotif: internal error (failed to read data) ... Too many open files
ClamFanotif: waiting for consumer thread to catch up then retrying ...
ClamWorker: performing scanning on file ''
ERROR: ClamClient: could not establish connection, Couldn't connect to server
``` 

## Output of lsof:
```bash
$ lsof -p 19914 | tail 
clamonacc 19914 root 1014u     sock                0,9      0t0 160537056 protocol: UNIX
clamonacc 19914 root 1015u     sock                0,9      0t0 160531432 protocol: UNIX
clamonacc 19914 root 1016u     sock                0,9      0t0 160531433 protocol: UNIX
clamonacc 19914 root 1017u     sock                0,9      0t0 160537812 protocol: UNIX
clamonacc 19914 root 1018u     sock                0,9      0t0 160537813 protocol: UNIX
clamonacc 19914 root 1019u     sock                0,9      0t0 160537816 protocol: UNIX
clamonacc 19914 root 1020u     sock                0,9      0t0 160537817 protocol: UNIX
clamonacc 19914 root 1021u     sock                0,9      0t0 160533068 protocol: UNIX
clamonacc 19914 root 1022u     sock                0,9      0t0 160533069 protocol: UNIX
clamonacc 19914 root 1023u     sock                0,9      0t0 160532346 protocol: UNIX
```
## I have to mention that my system supports a fair enough number of opened file descriptors:
```bash
$ ulimit -n
32768
```
## And increasing the values of MaxThreads and MaxQueue do not solve the issue:
```bash
$ clamconf | grep -iE "maxthreads|maxqueue"
MaxThreads = "1000"
MaxQueue = "1000"
OnAccessMaxThreads = "700"
```

Any help for this behavior ? 
Thanks in advance

**Comment by finchy** [comment]
Please report bugs at https://bugzilla.clamav.net.

**Comment by micahsnyder** [comment]
This repo and issue tracker are for the documentation.
Hi @Likkrid , as @finchy said bugzilla.clamav.net is our preferred location for bug reports for ClamAV.  I don't believe there is an existing ticket with your specific issue.  The only clamonacc connection isssue I'm aware of off-hand is https://bugzilla.clamav.net/show_bug.cgi?id=12563 so you may need to create a new bugzilla ticket if it seems to be unrelated.

As a side note, you can also get help from the community using the clamav mailing list https://lists.clamav.net/mailman/listinfo/clamav-users or on #clamav on irc.freenode.net or on Discord https://discord.gg/sGaxA5Q (linked with IRC using bots).
