### ISSUE TITLE
installing instructions for clamav on rhel/centos from EPEL are incorrect

### ISSUE THREAD

**Issue by captainjs** [Cisco-Talos/clamav-faq#140]
Hi,

RHEL/CentOS  
  yum install -y epel-release
  yum install -y clamav

Source: [https://www.clamav.net/documents/installing-clamav](url)

That's wrong. It will lead to incomplete installation.
It's also required to :
  yum install -y clamd

(otherwise it will be a partial install, and steps like this will not work:
[https://www.clamav.net/documents/on-access-scanning](url) )

I checked with EPEL apparently it's not an EPEL issue.

Can you please fix that?

**Comment by finchy** [comment]
Done with: https://github.com/Cisco-Talos/clamav-faq/commit/5260f5805787eeb0167212b0ef516bc61f00b69c
