### ISSUE TITLE
clamav-file-types out of date, missing EGG, PNG, GIF types

### ISSUE THREAD

**Issue by micahsnyder** [Cisco-Talos/clamav-faq#141]
The following are missing:
- CL_TYPE_PNG 
- CL_TYPE_GIF
- CL_TYPE_EGG

In addition, CL_TYPE_GRAPHICS handles JPEG & JPEG2000 in addition to TIFF (BE/LE).

**Comment by finchy** [comment]
Where is this listed?

**Comment by micahsnyder** [comment]
Sorry I should've said something. I'll handle it, I just added the ticket as a reminder.

**Comment by finchy** [comment]
Closed with #153
