### ISSUE TITLE
ClamAV Error Code

### ISSUE THREAD

**Issue by JeffinBao** [Cisco-Talos/clamav-faq#142]
Hi, first of all, thank you for creating ClamAV scanning engine. 
Currently, I am running ClamAV docker container in my local. I tested various files, however, for some file formats, Clamd returned "stream: Can't create temporary directory ERROR" after I upload the file. I thought file formats like PDF, ZIP are supported. 
Can I ask what type of ERROR it is? Or Does ClamAV actually support these file formats?
Thank you in advance.

**Comment by finchy** [comment]
Thank you for your interest in ClamAV.  While we receive a great number of requests, this is the GitHub repo for the FAQ itself.  We have thousands of people subscribed to our mailing lists, and it's better if you submit your questions to the appropriate mailing list at:

https://www.clamav.net/contact#ml

Please check out our ClamAV-Users mailing list there!  Thanks!
