### ISSUE TITLE
Virus detected on temp clamav files

### ISSUE THREAD

**Issue by darkneptune** [Cisco-Talos/clamav-faq#144]
Virus detected on temp clamav files: 

**C:\Users\xxx\AppData\Local\Temp\ClamWinPortableTemp\clamav-d94bb51f24c8f18991fd250a68ce0785.00001314.clamtmp**
-> **Trojan:Win32/Wacatac.B!ml**
`ClamWin:` 0.99.4.0

> ClamAV update process started at Wed Oct 14 18:59:13 2020
main.cld is up to date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Downloading daily-25951.cdiff [100%]
Downloading daily-25952.cdiff [100%]
Downloading daily-25953.cdiff [100%]
Downloading daily-25954.cdiff [100%]
Downloading daily-25955.cdiff [100%]
Downloading daily-25956.cdiff [100%]
Downloading daily-25957.cdiff [100%]
daily.cld updated (version: 25957, sigs: 4330982, f-level: 63, builder: raynman)
bytecode.cld is up to date (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
Database updated (8895978 signatures) from database.clamav.net (IP: 104.16.219.84)

**Comment by micahsnyder** [comment]
This is an issue tracker for issues with the ClamAV documentation. 

There are a variety of ways you can get in touch with the ClamAV Team, to get help from the ClamAV community, and to report ClamAV bugs, report new malware or malware false positives or notify us of new malware. See https://www.clamav.net/contact details.

Regarding your detected virus, it's not clear what your question is. You will need to be more specific about the exact issue you're facing.  Also bare in mind that ClamWin is a community project for Windows and is not made by our team. You will probably have better luck asking here: http://forums.clamwin.com/
