### ISSUE TITLE
Power and Z Architectures?

### ISSUE THREAD

**Issue by Kenzku** [Cisco-Talos/clamav-faq#145]
Hej,

I was wondering if ClamAV supports RedHat on Power and Z Architectures? I did not see it is mentioned explicitly in the webpage.

I tried to consume ClamAV and build into images based on the installation instructions for RedHat, but I assumed that on the webpage was for AMD64?

**Comment by finchy** [comment]
Hello,

Thank you for your interest in ClamAV.  While we receive a great number of requests, we cannot answer them all individually.  We have thousands of people subscribed to our mailing lists, and it's better if you submit your questions to the appropriate mailing list at:

https://www.clamav.net/contact#ml

Please check out our ClamAV-Users mailing list there!  Thanks!

**Comment by Kenzku** [comment]
@finchy Hej, I tried to contact via the mailing list, but I got response saying:

Your message has been rejected, probably because you are not
subscribed to the mailing list and the list's policy is to prohibit
non-members from posting to it.  If you think that your messages are
being rejected in error, contact the mailing list owner at
clamav-binary-owner@lists.clamav.net.

**Comment by finchy** [comment]
binary is not for you. clamav-users or even devel is for you.  Binary is for a different audience (package maintainers).

**Comment by finchy** [comment]
But, yes, you need to subscribe to post.
