### ISSUE TITLE
How does libclamav support multi thread?

### ISSUE THREAD

**Issue by chenzhongxiang** [Cisco-Talos/clamav-faq#150]
I've studied the libclamav interface and I have a question about supporting multi-threading, I understand that I need to allocate a separate engine for each thread, but each engine needs to load its own virus database which will require a lot of memory, on my machine one engine uses about 1gb of memory after loading the virus database.
How can I do multi-threading gracefully, or missing something?

**Comment by micahsnyder** [comment]
@chenzhongxiang you do not need a separate engine for each thread.  ClamD does multi-threaded scans using one engine.  pthreads support is build-in to protect critical variables.

I think multi-threading was added to the existing libclamav design somewhat poorly. libclamav was not originally designed with multi-threading in mind. Specifically, If you scan an archive or other file with embedded content, there is no easy way for scans of the embedded files to occur in new threads.

You'll have to reverse-engineer the ClamD source to understand how ClamD does it.  I haven't directly worked on that code myself and would have to do the same to give you a better answer.

Regards,
Micah
