### ISSUE TITLE
clamscan take long time

### ISSUE THREAD

**Issue by MandiYang** [Cisco-Talos/clamav-faq#156]
Hi, clamav currently can't scan big files, it will take very long time because of it takes long time to read all the signatures. Please make it faster at scanning files.

**Comment by micahsnyder** [comment]
Hi @MandiYang 

This ticket queue is for issues with the clamav documentation.  Please visit https://bugzilla.clamav.net/enter_bug.cgi?product=ClamAV if you need to create a bug report or feature request.

We're aware that loading the signature databases takes a long time and that larger files also take longer to scan.  The team which creates signature content for our official databases is actively working on reducing the database size by pruning older signatures that aren't performing.  RAM size for our daily database has reduced from 852 MB to 774 MB this month, with load time down 14.7% in our tests as well.  I am optimistic that they'll be able to continue this downward trend for a while without sacrificing efficacy. 

Cheers,
Micah
