### ISSUE TITLE
Update server is not available for iranian users

### ISSUE THREAD

**Issue by GreatBahram** [Cisco-Talos/clamav-faq#158]
Hello there,

I wanted to update the ClamAV engine database, and I used the `freshclam`, but the client cannot download the database files due to the restriction which Cloudflare imposes.

```shelll
Feb 25 17:21:57 host freshclam[166007]: Thu Feb 25 17:21:57 2021 -> ClamAV update process started at Thu Feb 25 17:21:57 2021
Feb 25 17:21:57 host freshclam[166007]: Thu Feb 25 17:21:57 2021 -> daily database available for download (remote version: 26091)
Feb 25 17:21:58 host freshclam[166007]: Thu Feb 25 17:21:58 2021 -> ^downloadFile: Unexpected response (403) from https://database.clamav.net/daily.cvd
Feb 25 17:21:58 host freshclam[166007]: Thu Feb 25 17:21:58 2021 -> ^getcvd: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Feb 25 17:21:58 host freshclam[166007]: Thu Feb 25 17:21:58 2021 -> Trying again in 5 secs...
```

**Comment by finchy** [comment]
Can you give me the IP you are reaching out to with fresh clam?  403 means you're specifically denied.

**Comment by GreatBahram** [comment]
I tried it on multiple internet service providers, and I can assure you the result was the same. Below you can see the error code and my IP address:

![Screenshot from 2021-02-26 11-44-41](https://user-images.githubusercontent.com/14103831/109273927-16b64100-7828-11eb-99ac-bcbd0eb68ce7.png)

**Comment by finchy** [comment]
Ah, I missed the subject of this.  We are blocked by corporate policy to not allow traffic from Iranian IP space.

**Comment by GreatBahram** [comment]
Thanks
