### ISSUE TITLE
Viral DB download issue du to firewall restriction on web site link

### ISSUE THREAD

**Issue by Stoony** [Cisco-Talos/clamav-faq#159]
Hi there,
it seems that for a few days, we are not able anymore to download the DB from : 
http://database.clamav.net/main.cvd 
This URL which is still on the download page (https://www.clamav.net/downloads) lead to a cloudfare error 
```
Error 1020 Ray ID: 62ccfd73eab068fa • 2021-03-08 15:10:23 UTC
Access denied
```

**Comment by finchy** [comment]
Thank you for writing in, please see the below:

https://lists.clamav.net/pipermail/clamav-users/2021-March/010577.html

**Comment by micahsnyder** [comment]
@Stoony Are you maintaining a private mirror?
