### ISSUE TITLE
scan mobile phone

### ISSUE THREAD

**Issue by PychoPc** [Cisco-Talos/clamav-faq#50]
Is it possible to scan a android mobile phone connected over mtp?
The reason is, I found a virus on my external memory card on the phone and now I want to scan the internal memory.
Using Linux Mint Mate 18.1 

Thanks in advance
Tom

**Comment by vrtadmin** [comment]
Please direct your questions to the mailing list.  http://lists.clamav.net/cgi-bin/mailman/listinfo/clamav-users
