### ISSUE TITLE
Possible bug in todays daily DB update

### ISSUE THREAD

**Issue by kratochviljan** [Cisco-Talos/clamav-faq#52]
LibClamAV Error: cli_ac_addsig: Signature for Win.Worm.Fadok-6328944-0 is too short
LibClamAV Error: cli_parse_add(): Problem adding signature (3).
LibClamAV Error: Problem parsing database at line 2793
LibClamAV Error: Can't load daily.ldb: Malformed database
LibClamAV Error: cli_tgzload: Can't load daily.ldb
LibClamAV Error: Can't load C:\ClamAV\db\daily.cld: Malformed database
ERROR: Malformed database

**Comment by kratochviljan** [comment]
DB files from 14/06/2017 are working fine, any younger has the mentioned problems.
I checked this twice on two different installations of ClamAV.

**Comment by vrtadmin** [comment]
This has been resolved.
