### ISSUE TITLE
HowTo: Update (refresh) Virus Database

### ISSUE THREAD

**Issue by LandisTwo** [Cisco-Talos/clamav-faq#57]
Thank you for clamav, but..
No where on website, documentation, --help | grep database, etc could i find the simple instruction:
after installing clamav, use **freshclam** (-v) to update the virus database.
A search for update, update database, refresh db, etc returns Nothing about
FreshClam
Only a search of /usr/bin/ for '*clam*' reveals 'FreshClam'
and # **freshclam** --help tells me how to use, sort-of.
Please add:
'**refresh / update Database w freshclam**' to 'Documentation FAQ'.

Thanks Again,
Landis.

**Comment by tmccourt** [comment]
Corrected the wording: commit below.
1c40453d0fedb0b88289791d9bec9603e9c0031c

**Comment by LandisTwo** [comment]
tmccourt
Thanks, but...
[1c40453](https://github.com/Cisco-Talos/clamav-faq/commit/1c40453d0fedb0b88289791d9bec9603e9c0031c)
There is still nothing indicating 'update / refresh **virus definition database**'
'signatures' sounds more like a md5 key, or 'security something' to avg user.
These terms are what I was looking for:
'update database' [db]
'refresh database'
'update virus db'
'**update virus definitions**'
'get latest virus definition file'
etc.
use the same wording in the warning clamav gives when run & database is out of date. I can't give you exact wording right now, as my db is up-to--date

thanks again, 
Landis.

**Comment by tmccourt** [comment]
commit 5ae9d68d90bf8dec83b4a0f8f5c1a0a04a6b69aa
