### ISSUE TITLE
Update Frequency

### ISSUE THREAD

**Issue by pzttb00m** [Cisco-Talos/clamav-faq#69]
Operate a standalone system that utilizes ClamAV.  At what frequency are main.cvd and bytecode.cvd updated?  Is the main.cvd a product of the daily.cvds?  Need to ensure when to download main.cvd versus daily.cvd.  thank you in advance.

**Comment by tmccourt** [comment]
You will want to download both.  Daily are updated every day. Main is less frequent but if you are doing a "freshclam" command, it will update daily, main and bytecode.cvd's.
