### ISSUE TITLE
a bad url in clamdoc.pdf

### ISSUE THREAD

**Issue by qux-bbb** [Cisco-Talos/clamav-faq#75]
In https://github.com/Cisco-Talos/clamav-faq/blob/master/manual/clamdoc.pdf，1.3 Virus submitting .
The url is bad, and the url should be https://www.clamav.net/reports/malware .

**Comment by micah-at-talos** [comment]
Thanks for the report.  It appears that we forgot to update the copies of the clam pdf documentation in clamav-faq from the latest release ( https://git.vrt.sourcefire.com/clamav/clamav-devel/blob/clamav-0.100.0/docs/clamdoc.pdf ).

For version 0.101 development, we're moving to a markdown format for this documentation, which currently can be viewed here https://github.com/Cisco-Talos/clamav-devel/blob/dev/0.101/docs/UserManual.md  We have yet to integrate the new clamav user manual format into the clamav.net website.
