### ISSUE TITLE
Duplicate and more  strings in logs

### ISSUE THREAD

**Issue by ttsrg** [Cisco-Talos/clamav-faq#81]
When ClamTk found a virus , It writes double and more records to logs on ONE event.
Could you explain how I can resolve that problem?
Thanks

![image](https://user-images.githubusercontent.com/39533021/42518189-f15024bc-8469-11e8-89dc-533cbe5d2de4.png)

![image](https://user-images.githubusercontent.com/39533021/42518204-fc28f706-8469-11e8-96b5-d8d5984f8f6f.png)
![image](https://user-images.githubusercontent.com/39533021/42518242-1034cbd0-846a-11e8-9fc7-aef21471abd4.png)

**Comment by tmccourt** [comment]
You will want to direct your question to ClamTK, as we don't support that. It is third party.
https://dave-theunsub.github.io/clamtk/

If this is happening without ClamTK, in just the log files, please file the bug:
https://bugzilla.clamav.net/

or ask on the mailing list:
http://lists.clamav.net/cgi-bin/mailman/listinfo    (Users mailing list)
