### ISSUE TITLE
Updates are served via CDN => no more mirrors?

### ISSUE THREAD

**Issue by Delphinator** [Cisco-Talos/clamav-faq#84]
According to https://bugzilla.clamav.net/show_bug.cgi?id=12054 ClamAV recently switched to using Cloudflare for serving database updates. I assume the information about setting up mirrors in this repository is therefore obsolete?

**Comment by tmccourt** [comment]
Right now, we are evaluating how the CloudFlare mirrors are working out. We aren't accepting new mirrors at the moment, until we fully evaluate everything. The information isn't completely invalid (yet) depending on what we see with the evaluation.
