### ISSUE TITLE
Warning when verifying source package 

### ISSUE THREAD

**Issue by ishmartbuoy** [Cisco-Talos/clamav-faq#91]
gpg --verify clamav-0.100.2.tar.gz.sig 
gpg: Signature made Thursday 27 September 2018 12:45:33 AM IST using RSA key ID BCA5BFAD
gpg: Good signature from "Talos (Talos, Cisco Systems Inc.) <research@sourcefire.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 65ED 5139 93F0 8DA0 6F96  39A6 F13F 9E16 BCA5 BFAD

**Comment by finchy** [comment]
This is occurring because you do not trust the key.
