### ISSUE TITLE
Clamscan detects files as malware but VT doesn't

### ISSUE THREAD

**Issue by ishmartbuoy** [Cisco-Talos/clamav-faq#93]
When running ClamAV 0.100.2 on my system, ClamAV detects few files as malicious https://postimg.cc/k6NF4MXr.  
But, when I scan these files individually on VirusTotal, none of the files are being flagged as malicious. https://postimg.cc/Z0C547fH

**Comment by ishmartbuoy** [comment]
Screenshot of the file hashes are at https://postimg.cc/2VTrPCDk

**Comment by micah-at-talos** [comment]
This is a git repository for ClamAV documentation. 

As per the recommendations [here](https://github.com/Cisco-Talos/clamav-faq/blob/master/faq/faq-scan-alerts.md#reporting), if you believe these to be false positives - please report them to our malware research team using [this site](https://www.clamav.net/reports/fp).
